"""
Generate ETHFalcon test vectors for QuantumVault.sol integration test.

Usage:
    cd python-ref
    python -m Falcon_dilithium_py.generate_vault_test_vectors

Output:
    test/QuantumVaultReal.t.sol  — Solidity test with embedded real Falcon vectors
"""

import sys
import os

# Add falcon_ref to path
_REF = os.path.join(os.path.dirname(__file__), "Falcon_falcon", "falcon_ref")
sys.path.insert(0, _REF)

from .Falcon_falcon.falcon_eth import ETHFalcon256
from .Falcon_falcon.falcon_params import FALCON_256
from encoding import decompress
from falcon_sign import deserialize_to_poly, HEAD_LEN, SALT_LEN

Q   = FALCON_256["q"]           # 12289
N   = FALCON_256["n"]           # 256
ENC_S_LEN = FALCON_256["sig_bytelen"] - HEAD_LEN - SALT_LEN  # 315


def decode_sig(sig_bytes):
    """Decode raw Falcon signature into (salt: bytes, s1_unsigned: list[int])."""
    salt      = sig_bytes[HEAD_LEN : HEAD_LEN + SALT_LEN]   # 40 bytes
    s1_encoded = sig_bytes[HEAD_LEN + SALT_LEN :]
    s1_signed = decompress(s1_encoded, ENC_S_LEN, N)
    if s1_signed is False:
        raise ValueError("decompress() failed — invalid signature encoding")
    s1_unsigned = [int(c % Q) for c in s1_signed]
    return salt, s1_unsigned


def build_withdraw_msg(chain_id, vault_addr_hex, nonce, amount, to_addr_hex):
    """Build the withdrawal message.

    Must match Solidity abi.encodePacked:
        "SuVa:withdraw:" || chainId(32B) || vault(20B) || nonce(32B) || amount(32B) || to(20B)
    """
    vault_b = bytes.fromhex(vault_addr_hex.lstrip("0x").zfill(40))
    to_b    = bytes.fromhex(to_addr_hex.lstrip("0x").zfill(40))
    return (
        b"SuVa:withdraw:"
        + chain_id.to_bytes(32, "big")
        + vault_b
        + nonce.to_bytes(32, "big")
        + amount.to_bytes(32, "big")
        + to_b
    )


def sol_array_256(arr, name, indent=8):
    """Render a Python list of 256 ints as Solidity uint256[256] memory assignments."""
    pad = " " * indent
    lines = [f"uint256[256] memory {name};"]
    for i, v in enumerate(arr):
        lines.append(f"{name}[{i}] = {v};")
    return f"\n{pad}".join(lines)


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    print("[*] Generating Falcon-256 keypair...")
    sk, vk = ETHFalcon256.keygen()
    h = deserialize_to_poly(vk, N)   # correct: list[int] in [0, q-1]

    # Parameters matching the Foundry test environment.
    # Foundry default chain ID is 31337.
    #
    # Vault deployment address is deterministic: the Foundry test contract is
    # always deployed at 0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496 with
    # deployer nonce starting at 1.  setUp() deploys in order:
    #   nonce=1 → ZKNOX_ethfalcon  (falcon_verifier)
    #   nonce=2 → MockERC20        (mock_usdt)
    #   nonce=3 → qUSDT            (q_impl)
    #   nonce=4 → QuantumVault     (v_impl / vault)  ← THIS IS THE VAULT
    # So vault address = CREATE(0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496, 4)
    #                  = 0x5991a2df15a8f6a256d3ec51e99254cd3fb576a9

    CHAIN_ID   = 31337
    # EIP-55 checksummed address of the vault at deployer nonce=4
    VAULT_ADDR = "0x5991A2dF15A8F6A256D3Ec51E99254Cd3fb576A9"
    NONCE      = 0
    AMOUNT     = 1_000_000   # 1 USDT (6 decimals)
    TO_ADDR    = "0x000000000000000000000000000000000000DEAD"

    print("[*] Building withdrawal message ...")
    msg = build_withdraw_msg(CHAIN_ID, VAULT_ADDR, NONCE, AMOUNT, TO_ADDR)

    print("[*] Signing ...")
    sig = ETHFalcon256.sign(sk, msg)
    salt, s1 = decode_sig(sig)

    # Self-verify before writing
    ok = ETHFalcon256.verify(vk, msg, sig)
    assert ok, "Self-verification FAILED — aborting"
    print(f"[+] Self-verification: OK  (sig size = {len(sig)} bytes)")

    # ── Solidity test ─────────────────────────────────────────────────────────
    h_sol  = sol_array_256(h,  "h")
    s1_sol = sol_array_256(s1, "s1")

    sol = f"""// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.25;
// Auto-generated by generate_vault_test_vectors.py -- DO NOT EDIT

import {{Test, console}} from "forge-std/Test.sol";
import {{QuantumVault}}   from "../src/QuantumVault.sol";
import {{qUSDT}}          from "../src/qUSDT.sol";
import {{MockERC20}}      from "../src/MockERC20.sol";
import {{ZKNOX_ethfalcon}} from "../src/ZKNOX_ethfalcon.sol";

/**
 * @notice Integration test using real ETHFalcon-256 vectors.
 *
 *         Deployment order (determines vault address):
 *           nonce=1  ZKNOX_ethfalcon  (falcon_verifier)
 *           nonce=2  MockERC20        (mock_usdt)
 *           nonce=3  qUSDT            (quantum_usdt)
 *           nonce=4  QuantumVault     (vault)  <-- address used when signing
 *
 *         Signed message parameters:
 *           chainId   = {CHAIN_ID}
 *           vaultAddr = {VAULT_ADDR}
 *           nonce     = {NONCE}
 *           amount    = {AMOUNT}
 *           to        = {TO_ADDR}
 */
contract QuantumVaultRealTest is Test {{
    QuantumVault    vault;
    qUSDT           quantum_usdt;
    MockERC20       mock_usdt;
    ZKNOX_ethfalcon falcon_verifier;

    address user      = address(0xBEEF);
    address recipient = address(0xDEAD);

    function setUp() public {{
        // Deploy in EXACTLY this order so vault lands at nonce=4 =
        // {VAULT_ADDR}
        falcon_verifier = new ZKNOX_ethfalcon();           // nonce 1
        mock_usdt       = new MockERC20();                 // nonce 2
        quantum_usdt    = new qUSDT(address(0));           // nonce 3
        vault           = new QuantumVault(                // nonce 4
            address(falcon_verifier),
            address(mock_usdt),
            address(quantum_usdt)
        );
        quantum_usdt.setVault(address(vault));

        // Verify deployment address matches what was signed
        require(
            address(vault) == {VAULT_ADDR},
            "vault address mismatch -- re-run generate_vault_test_vectors.py"
        );

        // Fund user
        mock_usdt.mint(user, 10_000_000);
        vm.prank(user);
        mock_usdt.approve(address(vault), type(uint256).max);
    }}

    // ── Real-vector test ──────────────────────────────────────────────────────
    /**
     * @notice End-to-end test: register key -> deposit -> withdraw with a real
     *         ETHFalcon-256 signature.
     */
    function testRealFalconWithdraw() public {{
        // ── Public key ────────────────────────────────────────────────────────
        {h_sol}

        // ── s1 coefficients ───────────────────────────────────────────────────
        {s1_sol}

        bytes memory salt   = hex"{salt.hex()}";
        uint256      amount = {AMOUNT};

        // Register key
        vm.prank(user);
        vault.registerKey(h);

        // Deposit
        vm.prank(user);
        vault.deposit(amount);
        assertEq(quantum_usdt.balanceOf(user), amount, "qUSDT not minted");

        // Withdraw with real Falcon signature
        vm.prank(user);
        vault.withdraw(h, salt, s1, amount, recipient);

        assertEq(mock_usdt.balanceOf(recipient), amount, "USDT not transferred to recipient");
        assertEq(quantum_usdt.balanceOf(user),   0,      "qUSDT not burned");
        assertEq(vault.nonces(user),             1,      "nonce not incremented");
    }}
}}
"""

    out_path = os.path.join(
        os.path.dirname(__file__), "..", "..", "test", "QuantumVaultReal.t.sol"
    )
    out_path = os.path.normpath(out_path)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(sol)

    print(f"[+] Written: {out_path}")
    print()
    print("Run the integration test with:")
    print("  cd ETHDILITHIUM-main && forge test --match-contract QuantumVaultRealTest -vv")


if __name__ == "__main__":
    main()
